---
#url: "https://petstore.swagger.io/v2/swagger.json"
url: "https://raw.githubusercontent.com/ioanabirsan/swagger-ui/master/taxi-service.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
